config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :recipes, path_names: {new: 'add_recipe'}

  resources :users, except: [:index, :show] 

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  root 'recipes#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    belongs_to :recipe
end

app/models/recipe.rb
class RecipeImageValidator < ActiveModel::Validator 
    def validate (record)
        if (record.image_url.blank?) 
            return 
        end
        image_str_len = record.image_url.length
        image_file_ext = record.image_url[record.image_url - 4, image_str_len - 1]
        unless image_file_ext == '.jpg' || image_file_ext == '.jpeg' || image_file_ext == '.gif' || image_file_ext == '.png' || image_file_ext == '.svg'
            record.errors[:image_url] << 'Image must be a JPG, JPEG, GIF, PNG, or SVG format'
        end
    end

end

class Recipe < ApplicationRecord
    include ActiveModel::Validations

    belongs_to :user
    has_many :ingredients

    validates :title, presence: true
    validates_with RecipeImageValidator
end

app/models/user.rb
class User < ApplicationRecord
    
    has_secure_password

    has_many :recipes

    validates :password, confirmation: true
    validates :first_name, :last_name, :email, :password, :password_confirmation, presence: true
    validates :first_name, :last_name, format: {with: /[a-zA-Z]/}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end 
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      #params.fetch(:recipe, {})
      params.require(:recipe).permit(:title, :description, :image_url, :minutes, :instructions)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        #render login page here
    end 

    def create
        #look up user by email and convert to lowercase to match email in db
        user = User.find_by(email: params[:login][:email].downcase)

        #verify user exists in db and run has_secure_password's authenticate()
        #to see if password submitted was correct
        if user && user.authenticate(params[:login][:password])
            #save the user.id in user's session cookie
            session[:user_id] = user.id.to_s
            redirect_to root_path, notice: 'Successfully logged in!'
        else 
            #re-render login page on incorrect email or password
            flash.now.alert = 'Incorrect email or password, try again.'
            render :new
        end 
    end

    def destroy
        # delete the saved user_id key/value from the cookie:
        session.delete(:user_id)
        redirect_to login_path, notice: "Logged out!"
    end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end 

    def create
        @user = User.new(user_params)
        @user.email.downcase!

        if User.find_by(email: @user.email)
            flash.now.alert = "Account already exists with email."
            render :new
        else 
            if @user.save
                flash[:notice] = "Account created successfully!"
                redirect_to root_url
            else
                flash.now.alert = "Oops, couldn't create account. Please make sure you are using a valid email and password and try again."
                render :new
            end  
        end  
    end

    def edit
        @user = User.find (params[:id])
    end

    def update
        @user = User.find (params[:id])
        if @user.update (user_params)
            redirect_to root_url
            #redirect_back fallback_location: root_url
        else 
            render :edit
        end 
    end

    private 
    def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Build My Own Cookbook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>	
    <% if notice %>
      <%= notice %>
    <% end %>
    
    <% if alert %>
      <%= alert %>
    <% end %>	
    <%= yield %>
  </body>
</html>

app/views/logins/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
        <!-- Email -->
        <div class="form-group">
            <input class="form-control"/>
        </div>

        <!-- Password -->
`        <div class="form-group">
            <input class="form-control"/>
        </div>
<% end %>

app/views/logins/new.html.erb
<section class="login">
    <div class="jumbotron">
        <h1 class="display-4">Build My Cookbook</h1>
        <p class="lead">Create a customized online cookbook full of recipes that you will love.</p>
        <p>Select savory creations from well-established sources, or add your own.</p>
    </div>

    <%= render 'form' %>
</section>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, local: true) do |form| %>
  <!-- title -->
  <div class="form-group">
    <%=form.label :title  %>
    <%=form.text_field :title, maxlength: 50, class: 'form-control' %>
  </div>

  <!-- description -->
   <div class="form-group">
    <%=form.label :description %>
    <%=text_area_tag :description, nil, class: 'form-control', rows: 2, cols: 25, maxlength: 100 %>
  </div>

  <!-- minutes -->
   <div class="form-group">
      <%=number_field :minutes, nil, min: 0, max: 999, class: 'form-control'%>
      <%=form.label :minutes%>
   </div>

   <!-- image -->
   <div class="form-group">
    <%=form.label :image_url, 'Recipe Image'%>
    <%= form.file_field :image_url %>
   </div>

   <!-- instructions -->
   <div class="form-group">
      <%=form.label :instructions %>
      <%=text_area_tag :instructions, nil, class: 'form-control', rows: 8, cols: 25 %>
   </div>

  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit class:'btn btn-primary'%>
  </div>
<% end %>

app/views/recipes/_header.html.erb
<header>
  <h1>Build My Cookbook</h1>
  <!--<h2>Create, and select recipes for your own online, customized cookbook</h2>-->
  <%=render 'nav'%>
</header>

app/views/recipes/_nav.html.erb
  <nav class='nav'>
    <%= link_to 'Show All Recipes', recipes_path, class: 'nav-link' %>
    <%= link_to 'New Recipe', new_recipe_path, class: 'nav-link' %>
  </nav>

app/views/recipes/edit.html.erb
<!--<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>-->
<%= render 'header'%>
<section class="recipe">

</section>
<%= render 'shared/footer'%>

app/views/recipes/index.html.erb
<%= render 'header'%>

<section class='recipe-list'>
  <h2>My Recipes</h2>
  <table>
    <thead>
      <tr>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @recipes.each do |recipe| %>
        <tr>
          <td><%= link_to 'Show', recipe %></td>
          <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
          <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>

<%= render 'shared/footer'%>

app/views/recipes/new.html.erb
<%= render 'header'%>


<section class="recipe">
    <h2>Add New Recipe</h2>
    <%= render 'form', recipe: @recipe %>
</section>


<%= render 'shared/footer'%>

app/views/recipes/show.html.erb
<!--<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>-->

<%= render 'header'%>

<section class="recipe">
</section>

<%= render 'shared/footer'%>

app/views/shared/_footer.html.erb
<footer>Copyright &copy; 2019 Chanel Henley</footer>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
    <!-- First Name -->
    <div class="form-group">
        <%=form.label :first_name %>
        <%=form.text_field :first_name, class: 'form-control' %>
    </div>

    <!-- Last Name -->
    <div class="form-group">
        <%=form.label :last_name  %>
        <%=form.text_field :last_name, class: 'form-control' %>
    </div>

    <!-- Email -->
    <div class="form-group">
        <%=form.label :email, 'Email (Username)'  %>
        <%=form.email_field :email, class:'form-control' %>
    </div>

    <!-- Password -->
    <div class="form-group">
        <%= form.label :password %>
        <%= form.password_field :password, class:'form-control' %>
    </div>

    <div class="form-group">
        <%= form.label :password, 'Confirm Password'%>
        <%= form.password_field :password_confirmation, class:'form-control' %>
    </div>

    <div class="actions">
        <%= form.submit 'Save', class:'btn btn-primary'%>
     </div>
<% end %>

app/views/users/_header.html.erb
<header>
  <h1>Build My Cookbook</h1>
</header>

app/views/users/edit.html.erb
<%= render 'header'%>

<section class="user">
    <h2>Update My Account</h2>
     <%= render 'form', user: @user %>
</section>

<%= render 'shared/footer'%>

app/views/users/new.html.erb
<%= render 'header'%>

<section class="user">
    <h2>Create an Account</h2>
    <%= render 'form', user: @user %>
</section>

<%= render 'shared/footer'%>